# Dockerfile

# Script       : IP-Tracker
# Author       : NAHID.JR
# Github       : https://github.com/hackingboyjr 
# Messenger    : https://m.me/mdnahidhasan008
# Email        : jrmdnahid022@gmail.com 
# Date         : 10-06-2024
# Main Language: Shell

# Download and import main images

# Operating system
FROM debian:latest

# Author info
LABEL MAINTAINER="https://github.com/hackingboyjr/IP-Tracker"

# Working directory
WORKDIR /IP-Tracker/
# Add files 
ADD . /IP-Tracker

# Installing other packages
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install curl unzip wget -y
RUN apt-get install --no-install-recommends php -y
RUN apt-get clean

# Main command
CMD ["./ip.sh", "--no-update"]

## Wanna run it own? Try following commnads:

## "sudo docker build . -t kasroudra/ip-tracker:latest", "sudo docker run --rm -it kasroudra/ip-tracker:latest"

## "sudo docker pull kasroudra/ip-tracker", "sudo docker run --rm -it kasroudra/ip-tracker"
